apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wellinton07/autoatendimento-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres:5432/autoatendimento"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: "info"
